"""
apps/wastewater_app/credibility_layer.py

Credibility Layer — Production V1
===================================

Final validation and enhancement layer. Reads UpgradePathway + FeasibilityReport
and produces a CredibleOutput — a complete, internally consistent, client-presentable
engineering recommendation.

This layer:
  - checks engineering rule consistency (e.g. EQ basin above 3× DWA)
  - ensures pathway completeness (Bardenpho reachable from TN-only, etc.)
  - enforces minimum 2 alternatives
  - adds technology compatibility flags (SBR+CoMag, MBR+IFAS, etc.)
  - clarifies ranking-vs-stack distinction
  - ensures residual risks are complete
  - enforces cause→mechanism→solution language
  - runs a final consistency check

Does NOT modify UpgradePathway or FeasibilityReport objects.
Returns CredibleOutput with all sections assembled for rendering.

Design principles
-----------------
- Pure functions, deterministic, fully explainable
- Every credibility note has a stated reason
- Language targets senior engineer / utility decision-maker
"""
from __future__ import annotations

from dataclasses import dataclass, field
from typing import Dict, List, Optional, Tuple

from apps.wastewater_app.stack_generator import (
    UpgradePathway, PathwayStage, AlternativePathway,
    TI_COMAG, TI_BIOMAG, TI_EQ_BASIN, TI_STORM_STORE,
    TI_INDENSE, TI_MIGINDENSE, TI_MEMDENSE,
    TI_HYBAS, TI_IFAS, TI_MBBR, TI_MABR,
    TI_BARDENPHO, TI_RECYCLE_OPT, TI_ZONE_RECONF,
    TI_DENFILTER, TI_TERT_P,
    CT_HYDRAULIC, CT_SETTLING, CT_NITRIFICATION,
    CT_TN_POLISH, CT_TP_POLISH, CT_BIOLOGICAL,
    CT_MEMBRANE, CT_WET_WEATHER,
    MECH_BALLASTED, MECH_HYD_EXP, MECH_BIOMASS_SEL,
    MECH_BIOFILM_RET, MECH_AER_INT, MECH_PROC_OPT,
    MECH_TERT_DN, MECH_TERT_P, MECH_MEMBRANE_SEL,
    _TECH_DISPLAY, _make_stage,
)
from apps.wastewater_app.feasibility_layer import FeasibilityReport, FS_HIGH, FS_MEDIUM, FS_LOW
from apps.wastewater_app.mbr_layer import assess_mbr_applicability, MBR_STRONG, MBR_MODERATE, MBR_WEAK


# ── Result dataclasses ─────────────────────────────────────────────────────────

@dataclass
class CredibilityNote:
    """A flag or note added by the credibility layer."""
    category:  str   # "Rule Consistency" / "Completeness" / "Compatibility" / "Language"
    severity:  str   # "Info" / "Warning" / "Correction"
    message:   str
    applied:   bool  # True if the note required a change to the output


@dataclass
class VerifiedAlternative:
    """An alternative pathway that has passed credibility checks."""
    label:          str
    mechanism_label:str
    stages:         List[str]    # tech display names in order
    rationale:      str
    when_preferred: str
    capex_class:    str
    is_generated:   bool = False   # True if added by credibility layer (not from stack_generator)


@dataclass
class ResidualRisk:
    """A single residual risk with category and urgency."""
    category:  str   # "Hydraulic" / "Chemical" / "Operational" / "Future trigger"
    risk:      str
    urgency:   str   # "Immediate" / "Planning horizon" / "Monitoring"


@dataclass
class CredibleOutput:
    """
    Complete, validated, client-presentable engineering recommendation.

    This is the final synthesis of UpgradePathway + FeasibilityReport
    after credibility checks have been applied.
    """
    # ── Source inputs (unchanged) ──────────────────────────────────────────────
    pathway:            UpgradePathway
    feasibility:        FeasibilityReport

    # ── Validated content ──────────────────────────────────────────────────────
    # Recommended stack (verified — same stages as pathway.stages)
    recommended_stages: List[PathwayStage]

    # Alternatives (pathway originals + any generated by credibility layer)
    alternatives:       List[VerifiedAlternative]

    # Structured residual risks
    residual_risks:     List[ResidualRisk]

    # ── Credibility checks ─────────────────────────────────────────────────────
    credibility_notes:  List[CredibilityNote]
    consistency_flags:  List[str]    # contradictions detected
    compatibility_flags:List[str]    # technology compatibility warnings

    # ── Narrative sections ─────────────────────────────────────────────────────
    executive_summary:      str    # 1–2 paragraph concept design recommendation
    why_stack_works:        str    # cause → mechanism → solution linkage
    ranking_clarification:  str    # standard ranking-vs-stack note
    feasibility_narrative:  str    # refined feasibility paragraph
    confidence_statement:   str    # final confidence with reason

    # ── Final status ───────────────────────────────────────────────────────────
    final_confidence:   str   # High / Medium / Low
    ready_for_client:   bool  # True if no Warning/Correction credibility notes remain


# ── Step 1: Rule consistency check ────────────────────────────────────────────

def _check_rule_consistency(
    pathway: UpgradePathway,
    plant_context: Dict,
) -> Tuple[List[CredibilityNote], List[VerifiedAlternative]]:
    """
    Enforce engineering rules that must appear in outputs.
    Returns (notes, generated_alternatives).
    """
    notes: List[CredibilityNote] = []
    gen_alts: List[VerifiedAlternative] = []
    flow_ratio   = plant_context.get("flow_ratio", 1.0) or 1.0
    ct_types     = {c.constraint_type for c in pathway.constraints}
    tech_in_stack= {s.technology for s in pathway.stages}

    # Rule: hydraulic attenuation required above 3× DWA
    # Fix 4: fire when flow_ratio >= 3.0 regardless of whether CoMag is in stack.
    # If CoMag IS present: emit Info note (not Warning) — CoMag provides relief but
    # does not eliminate the need for upstream attenuation at extreme peaks.
    # If CoMag is absent: emit Warning + generate EQ basin alternative (existing logic).
    _has_attenuation = TI_EQ_BASIN in tech_in_stack or TI_STORM_STORE in tech_in_stack
    _has_comag       = TI_COMAG in tech_in_stack or TI_BIOMAG in tech_in_stack

    if flow_ratio >= 3.0 and not _has_attenuation and _has_comag:
        # CoMag is present but extreme peaks still need complementary attenuation
        notes.append(CredibilityNote(
            category="Rule Consistency",
            severity="Info",
            message=(
                f"Peak flows exceed {flow_ratio:.1f}\u00d7 ADWF (above the \u223c3\u00d7 threshold). "
                "While high-rate clarification (CoMag / BioMag) provides significant hydraulic relief, "
                "extreme events may still require upstream attenuation (EQ basin, storm storage, "
                "or I/I reduction programme). Include attenuation infrastructure in the 15-year "
                "asset management plan."
            ),
            applied=False,   # informational — does not modify stack
        ))

    if flow_ratio >= 3.0 and TI_EQ_BASIN not in tech_in_stack and TI_COMAG not in tech_in_stack:
        notes.append(CredibilityNote(
            category="Rule Consistency",
            severity="Warning",
            message=(
                f"Flow ratio {flow_ratio:.1f}× DWA exceeds the 3× threshold where hydraulic "
                "attenuation is required as the primary intervention. "
                "EQ basin or storm storage should appear in the primary stack or alternatives."
            ),
            applied=True,
        ))
        gen_alts.append(VerifiedAlternative(
            label="Option — Hydraulic attenuation first (EQ basin / storm storage)",
            mechanism_label="Hydraulic expansion / attenuation storage",
            stages=["Equalisation / flow balancing basin", "Storm storage / attenuation infrastructure"],
            rationale=(
                f"At {flow_ratio:.1f}× DWA, extreme peak wet weather flows cannot be resolved by "
                "process intensification alone. An equalisation basin targeting ≤ 2× DWA at the "
                "secondary inlet is the most reliable hydraulic mitigation before any biological "
                "upgrade is commissioned."
            ),
            when_preferred=(
                "When overflow, bypass, or treatment disruption occurs during peak wet weather events. "
                "Must be addressed before biological upgrades are sized or commissioned."
            ),
            capex_class="High",
            is_generated=True,
        ))

    # Rule: TN-only case must have Bardenpho reachable
    if (CT_TN_POLISH in ct_types or CT_BIOLOGICAL in ct_types) and CT_NITRIFICATION not in ct_types:
        bardenpho_present = (TI_BARDENPHO in tech_in_stack or TI_RECYCLE_OPT in tech_in_stack)
        if not bardenpho_present:
            notes.append(CredibilityNote(
                category="Completeness",
                severity="Warning",
                message=(
                    "TN / biological performance limitation is active but Bardenpho zone "
                    "optimisation or recycle ratio optimisation does not appear in the stack or alternatives. "
                    "Process optimisation is the primary mechanism for carbon-limited TN."
                ),
                applied=True,
            ))
            gen_alts.append(VerifiedAlternative(
                label="Option — Process optimisation pathway (Bardenpho / recycle)",
                mechanism_label="Process optimisation",
                stages=["Recycle ratio optimisation", "Bardenpho / process zone optimisation"],
                rationale=(
                    "Where NH4 is controlled and TN remains elevated due to carbon-limited "
                    "denitrification, process zone reconfiguration and recycle optimisation are the "
                    "primary engineering response. Internal recycle R ≈ 2 recovers ~67% of nitrate "
                    "without capital spend. Bardenpho zone optimisation achieves further TN reduction "
                    "with modest civil works."
                ),
                when_preferred=(
                    "When nitrification is performing and the primary issue is NOx reduction. "
                    "Lower CAPEX and complexity than biological expansion."
                ),
                capex_class="Low",
                is_generated=True,
            ))

    # Rule: settling limitation must have at least two pathways (inDENSE and BioMag)
    if CT_SETTLING in ct_types:
        has_selection  = any(t in tech_in_stack for t in (TI_INDENSE, TI_MIGINDENSE, TI_BIOMAG, TI_MEMDENSE))
        has_ballasted  = TI_BIOMAG in tech_in_stack
        if has_selection and not has_ballasted:
            # Check whether BioMag appears in alternatives
            alt_techs = " ".join(a.label for a in pathway.alternatives)
            if "BioMag" not in alt_techs and "biomag" not in alt_techs.lower():
                gen_alts.append(VerifiedAlternative(
                    label="Option — BioMag (ballasted biology) as settling alternative",
                    mechanism_label="Ballasted settling / high-rate clarification",
                    stages=["BioMag® (ballasted MBBR-activated sludge hybrid)"],
                    rationale=(
                        "BioMag combines magnetic ballasted settling with integrated biological treatment. "
                        "Where clarifier loading is critical and MLSS is elevated, BioMag provides more "
                        "robust settling improvement than inDENSE alone by increasing sludge density and "
                        "settling velocity via magnetic microspheres."
                    ),
                    when_preferred=(
                        "When inDENSE alone is insufficient to resolve clarifier loading under peak "
                        "biological load, or where MLSS consistently exceeds 5,500 mg/L."
                    ),
                    capex_class="Medium",
                    is_generated=True,
                ))

    return notes, gen_alts


# ── Step 2: Completeness check ────────────────────────────────────────────────

def _check_completeness(
    pathway: UpgradePathway,
) -> Tuple[List[CredibilityNote], List[VerifiedAlternative]]:
    """Ensure no pathway stops prematurely."""
    notes: List[CredibilityNote] = []
    gen_alts: List[VerifiedAlternative] = []
    ct_types     = {c.constraint_type for c in pathway.constraints}
    tech_in_stack= {s.technology for s in pathway.stages}

    # Nitrification: ensure IFAS vs MABR alternatives exist
    if CT_NITRIFICATION in ct_types:
        biofilm_in_stack = any(t in tech_in_stack for t in (TI_IFAS, TI_HYBAS, TI_MBBR, TI_MABR))
        alt_labels = " ".join(a.label for a in pathway.alternatives).lower()
        has_mabr_alt = "mabr" in alt_labels or "mabr" in " ".join(
            s.technology for s in pathway.stages).lower()
        has_ifas_alt = any(t in tech_in_stack for t in (TI_IFAS, TI_HYBAS, TI_MBBR))

        if biofilm_in_stack and not has_mabr_alt:
            gen_alts.append(VerifiedAlternative(
                label="Option — MABR OxyFAS as aeration-efficient nitrification alternative",
                mechanism_label="Aeration intensification (membrane O₂ delivery)",
                stages=["MABR OxyFAS® (membrane-aerated biofilm reactor)"],
                rationale=(
                    "MABR delivers oxygen directly to the biofilm via hollow-fibre membranes at "
                    "up to 14 kgO₂/kWh — 7–10× more efficient than conventional diffused aeration. "
                    "Where aeration capacity is constrained, MABR provides nitrification intensification "
                    "without blower expansion. NHx <0.1 mg/L is achievable across a wide load range "
                    "(Kawana modelling calibration)."
                ),
                when_preferred=(
                    "When aeration blower capacity is constrained or energy minimisation is a "
                    "strategic priority. Suitable for plants where blower expansion is not feasible."
                ),
                capex_class="Medium",
                is_generated=True,
            ))
        elif not biofilm_in_stack and not has_ifas_alt:
            notes.append(CredibilityNote(
                category="Completeness",
                severity="Info",
                message=(
                    "Nitrification limitation identified but no biofilm retention technology appears "
                    "in the stack. IFAS or MABR should be considered as primary or alternative."
                ),
                applied=False,
            ))

    return notes, gen_alts


# ── Step 3: Ensure minimum 2 alternatives ────────────────────────────────────

def _ensure_minimum_alternatives(
    pathway: UpgradePathway,
    existing_gen: List[VerifiedAlternative],
    feasibility: FeasibilityReport,
) -> Tuple[List[VerifiedAlternative], List[CredibilityNote]]:
    """Ensure at least 2 credible alternatives exist (from any source)."""
    notes: List[CredibilityNote] = []
    # Convert existing pathway.alternatives to VerifiedAlternative
    verified: List[VerifiedAlternative] = []
    for a in pathway.alternatives:
        verified.append(VerifiedAlternative(
            label=a.label, mechanism_label="",
            stages=a.stages, rationale=a.rationale,
            when_preferred=a.when_preferred, capex_class=a.capex_class,
        ))

    # Add feasibility lower-risk alternative if present
    if feasibility.lower_risk_alternative:
        lra = feasibility.lower_risk_alternative
        tech_list = [c.split("→")[-1].strip() for c in lra.stage_changes]
        verified.append(VerifiedAlternative(
            label=lra.label,
            mechanism_label="Reduced-risk configuration",
            stages=tech_list,
            rationale=lra.rationale,
            when_preferred=" ".join(lra.trade_offs[:2]),
            capex_class=lra.capex_impact if lra.capex_impact in ("Low","Medium","High") else "Medium",
            is_generated=True,
        ))

    # Add generated alternatives
    verified.extend(existing_gen)

    # Deduplicate by label
    seen_labels = set()
    deduped = []
    for v in verified:
        if v.label not in seen_labels:
            deduped.append(v)
            seen_labels.add(v.label)

    # If fewer than 2, generate a civil expansion fallback
    if len(deduped) < 2:
        notes.append(CredibilityNote(
            category="Completeness",
            severity="Info",
            message="Fewer than 2 alternatives existed — civil expansion fallback added.",
            applied=True,
        ))
        deduped.append(VerifiedAlternative(
            label="Option — Conventional civil expansion (last resort)",
            mechanism_label="Civil expansion",
            stages=["Secondary clarifier expansion", "New bioreactor volume",
                    "Additional blower / aeration capacity"],
            rationale=(
                "Conventional civil expansion addresses all constraints through volume addition "
                "rather than process efficiency. Should only be pursued after intensification options "
                "are fully evaluated and demonstrably exhausted."
            ),
            when_preferred=(
                "When the intensification envelope is exhausted, performance targets are not achievable "
                "through biological or hydraulic optimisation, or footprint constraints do not apply."
            ),
            capex_class="High",
            is_generated=True,
        ))

    return deduped[:5], notes   # cap at 5 alternatives


# ── Step 4: Technology compatibility flags ────────────────────────────────────

def _check_compatibility(
    pathway: UpgradePathway,
    plant_context: Dict,
) -> List[str]:
    """Return list of compatibility warnings."""
    flags = []
    is_sbr = plant_context.get("is_sbr", False)
    is_mbr = plant_context.get("is_mbr", False)
    tech_in_stack = {s.technology for s in pathway.stages}

    # SBR + CoMag
    if is_sbr and TI_COMAG in tech_in_stack:
        flags.append(
            "SBR + CoMag: CoMag is a continuous-flow high-rate clarifier. Integration with a "
            "batch SBR process requires a dedicated side-stream or bypass configuration — it cannot "
            "be installed inline with SBR decant. A bypass lane or storm-event bypass loop must be "
            "designed. EQ basin may be a simpler primary hydraulic option for SBR plants."
        )

    # MBR + IFAS/MBBR (potential incompatibility)
    if is_mbr and any(t in tech_in_stack for t in (TI_IFAS, TI_MBBR)):
        flags.append(
            "MBR + IFAS/MBBR: Carrier media in an MBR can enter membrane tanks and cause membrane "
            "damage unless dedicated media retention screens are installed upstream of the membrane "
            "tank inlet. This is a manageable engineering constraint but requires explicit design "
            "provision — not a standard IFAS/MBBR installation."
        )

    # CoMag / BioMag magnetite dependency note
    if any(t in tech_in_stack for t in (TI_COMAG, TI_BIOMAG)):
        tech_name = "CoMag" if TI_COMAG in tech_in_stack else "BioMag"
        flags.append(
            f"{tech_name}: Continuous magnetite supply and on-site magnetic recovery system "
            "are required. Recovery efficiency (typically >99.5%) determines whole-of-life cost. "
            "Establish pre-qualified supplier agreements and local stock before commissioning."
        )

    # DNF + high DO carryover risk
    if TI_DENFILTER in tech_in_stack:
        flags.append(
            "Denitrification Filter: DO carryover from secondary treatment must be controlled to "
            "< 0.5 mg/L at the filter inlet. Elevated DO from the biological stage will suppress "
            "denitrification regardless of methanol dose. Assess secondary effluent DO profile "
            "before filter sizing."
        )

    # ── MBR architecture notes (v24Z41) ───────────────────────────────────────
    if is_mbr:
        mbr_report = assess_mbr_applicability(plant_context)
        # Architecture role and fit level
        fit_prefix = {MBR_STRONG: "Strong fit", MBR_MODERATE: "Moderate fit",
                      MBR_WEAK: "Weak fit"}.get(mbr_report.fit_level, "")
        fit_note = (
            f"MBR architecture ({fit_prefix}): {mbr_report.architecture_role} "
            f"{mbr_report.energy_note} "
            f"{mbr_report.operations_note} "
            f"{mbr_report.lifecycle_note}"
        )
        flags.append(fit_note)
        # Existing MBR guidance
        if mbr_report.existing_mbr_note:
            flags.append(mbr_report.existing_mbr_note)
        # Weak fit warning
        if mbr_report.weak_fit_factors:
            flags.append(
                "MBR weak-fit factors for this scenario: "
                + " ".join(mbr_report.weak_fit_factors)
            )
        # MABR differentiation — always include when is_mbr to prevent confusion
        flags.append(mbr_report.mabr_differentiation)
        # Decision tension
        flags.append(mbr_report.decision_tension)

    return flags


# ── Step 5: Ranking vs stack clarification ────────────────────────────────────

_RANKING_CLARIFICATION = (
    "Technology ranking (in the brownfield scoring table) reflects long-term replacement or "
    "full conversion potential for each technology type, scored against the identified constraints. "
    "The recommended stack is a different output: it represents a staged brownfield upgrade pathway "
    "that sequences targeted intensification technologies within the existing plant footprint. "
    "These two outputs are complementary — the ranking identifies what could eventually replace the "
    "plant; the stack identifies what should be added first to extend its serviceable life."
)


# ── Step 6: Structured residual risks ────────────────────────────────────────

def _build_residual_risks(
    pathway: UpgradePathway,
    feasibility: FeasibilityReport,
    flow_ratio: float,
) -> List[ResidualRisk]:
    """Build a complete, categorised residual risk list."""
    risks: List[ResidualRisk] = []
    tech_in_stack = {s.technology for s in pathway.stages}
    ct_types      = {c.constraint_type for c in pathway.constraints}

    # Always: hydraulic peaks
    risks.append(ResidualRisk(
        category="Hydraulic",
        risk=(
            f"Extreme wet weather flows (> 3× DWA) may still require upstream sewer attenuation "
            f"or storm storage even after the process upgrade stack is implemented. "
            f"{'(Current flow ratio is ' + str(round(flow_ratio,1)) + '× DWA — hydraulic attenuation is already required.)' if flow_ratio >= 3.0 else ''}"
        ).strip(),
        urgency="Planning horizon" if flow_ratio < 2.0 else "Immediate",
    ))

    # Chemical dependency
    if feasibility.chemical_dependency in ("Medium", "High"):
        risks.append(ResidualRisk(
            category="Chemical",
            risk=(
                "Chemical supply dependency persists after upgrade. "
                + ("Methanol supply disruption halts tertiary denitrification. "
                   if TI_DENFILTER in tech_in_stack else "")
                + "Dual-supply agreements and on-site storage should be established before commissioning."
            ),
            urgency="Planning horizon",
        ))

    # TN carbon limitation
    if (CT_TN_POLISH in ct_types or CT_BIOLOGICAL in ct_types) and TI_DENFILTER not in tech_in_stack:
        risks.append(ResidualRisk(
            category="Chemical",
            risk=(
                "TN compliance may require external carbon dosing (methanol or acetate) if COD/N < 4 "
                "after internal recycle optimisation. Quantify COD/N ratio and assess carbon supplementation "
                "requirement before designing final TN strategy."
            ),
            urgency="Planning horizon",
        ))

    # Operational complexity
    if len(pathway.stages) >= 3 or feasibility.operational_complexity in ("High", "Medium"):
        risks.append(ResidualRisk(
            category="Operational",
            risk=(
                f"A {len(pathway.stages)}-stage upgrade increases operational complexity. "
                "Staged commissioning with effluent monitoring between each stage is essential. "
                "Operator training and specialist OEM support agreements should be established "
                "before commissioning."
            ),
            urgency="Planning horizon",
        ))

    # Biofilm establishment
    if any(t in tech_in_stack for t in (TI_IFAS, TI_HYBAS, TI_MBBR, TI_MABR)):
        risks.append(ResidualRisk(
            category="Operational",
            risk=(
                "Biofilm establishment takes 4–8 weeks after media installation. "
                "Effluent monitoring triggers should be adjusted during the establishment period. "
                "WAS rate and aeration control strategy must be recalibrated once biofilm is active."
            ),
            urgency="Monitoring",
        ))

    # Future upgrade trigger
    risks.append(ResidualRisk(
        category="Future trigger",
        risk=(
            "If flow growth or licence tightening occurs beyond the intensified envelope, "
            "the next upgrade trigger is: "
            + ("civil expansion (new secondary clarifier or bioreactor volume) "
               if CT_SETTLING in ct_types else
               "expansion of biological capacity (additional media or module count) ")
            + "or catchment-level I/I reduction programme."
        ),
        urgency="Planning horizon",
    ))

    return risks


# ── Step 7: Narrative enforcement ────────────────────────────────────────────

def _executive_summary(pathway: UpgradePathway, feasibility: FeasibilityReport) -> str:
    """Generate a cause→mechanism→solution executive summary."""
    pc    = pathway.primary_constraint
    state = pathway.system_state
    prox  = pathway.proximity_pct
    n_stages = len(pathway.stages)
    conf  = feasibility.adjusted_confidence

    # Primary constraint in cause → mechanism → solution language
    cause_map = {
        "hydraulic_limitation":             "hydraulically constrained under peak wet weather conditions",
        "wet_weather_peak":                 "exposed to peak wet weather flows that exceed design capacity",
        "settling_limitation":              "settling-limited, with solids carry-over risk under rising load",
        "nitrification_limitation":         "nitrification-limited due to insufficient effective sludge age",
        "tn_polishing_limitation":          "TN-limited due to carbon-available denitrification deficit",
        "tp_polishing_limitation":          "TP-limited, requiring tertiary chemical polishing",
        "biological_performance_limitation":"biologically underperforming relative to licence targets",
        "membrane_performance_limitation":  "membrane performance-limited by biomass quality and fouling",
    }
    cause = cause_map.get(pc.constraint_type,
                          pc.label.lower() + " limited")

    # Stage description
    if n_stages == 1:
        stage_desc = f"a targeted {pathway.stages[0].tech_display.split('(')[0].strip()} installation"
    elif n_stages == 2:
        stage_desc = (f"{pathway.stages[0].tech_display.split('(')[0].strip()} "
                      f"followed by {pathway.stages[1].tech_display.split('(')[0].strip()}")
    else:
        stage_desc = (f"a {n_stages}-stage intensification sequence "
                      f"({', '.join(s.tech_display.split('(')[0].strip() for s in pathway.stages[:3])})")

    summary_p1 = (
        f"The {pathway.plant_type} plant is currently {cause} "
        f"at {prox:.0f}% of design capacity ({state}). "
        f"The recommended upgrade pathway is {stage_desc}, addressing the primary constraint "
        f"through {pathway.stages[0].mechanism_label.lower() if pathway.stages else 'process intensification'} "
        f"without requiring major civil expansion."
    )

    summary_p2 = (
        f"Feasibility is assessed as {feasibility.overall_feasibility} "
        f"with {conf} confidence. "
        + (f"The primary feasibility consideration is {feasibility.supply_chain_risk.lower()} "
           f"supply chain risk and {feasibility.chemical_dependency.lower()} chemical dependency. "
           if feasibility.chemical_dependency != "None" else
           f"The stack is operationally straightforward with low supply chain dependency. ")
        + ("A lower-risk alternative is available — see Alternative Pathways."
           if feasibility.lower_risk_alternative else
           "No significant feasibility concerns are identified with the recommended pathway.")
    )

    return f"{summary_p1}\n\n{summary_p2}"


def _why_stack_works(pathway: UpgradePathway) -> str:
    """Generate cause → mechanism → solution linkage for the full stack."""
    if not pathway.stages:
        return "Insufficient data to generate stack rationale."
    parts = [
        "This upgrade pathway is sequenced to address the highest-priority constraint first, "
        "with each stage unlocking the next and avoiding functional redundancy.\n"
    ]
    for s in pathway.stages:
        parts.append(
            f"Stage {s.stage_number} — {s.tech_display.split('(')[0].strip()}: "
            f"{s.purpose} {s.engineering_basis[:120]}".rstrip() + "."
        )
    parts.append(
        "\nTechnologies have been selected to exhaust process intensification options "
        "before recommending civil expansion, consistent with the principle that intensification "
        "should precede volume addition in brownfield upgrade planning."
    )
    return "\n".join(parts)


def _feasibility_narrative(feasibility: FeasibilityReport) -> str:
    """Refined feasibility paragraph using consultant language."""
    dim_map = {d.dimension: d.score for d in feasibility.dimensions}
    high_risks = [d.dimension for d in feasibility.dimensions
                  if d.score in (FS_MEDIUM, FS_LOW)]

    if not high_risks:
        return (
            "This solution is technically robust with low operational dependency and a broad supply base. "
            "All six feasibility dimensions score positively. "
            f"{feasibility.feasibility_summary}"
        )
    dims_str = ", ".join(high_risks[:3])
    return (
        f"Feasibility is {feasibility.overall_feasibility.upper()} overall, with moderate attention "
        f"required on: {dims_str}. "
        + ("This solution introduces supply chain dependency on specialist materials — "
           "pre-qualification of suppliers and contingency stock management are recommended. "
           if feasibility.supply_chain_risk == "High" else "")
        + ("Operational complexity increases due to chemical dosing and process control requirements. "
           if feasibility.chemical_dependency in ("Medium", "High") else "")
        + (f"Mitigations: {'; '.join(feasibility.key_mitigations[:2])}."
           if feasibility.key_mitigations else "")
    )


# ── Step 8: Consistency check ─────────────────────────────────────────────────

def _consistency_check(
    pathway: UpgradePathway,
    feasibility: FeasibilityReport,
    alternatives: List[VerifiedAlternative],
) -> List[str]:
    """Detect contradictions between outputs."""
    flags: List[str]  = []
    tech_in_stack     = {s.technology for s in pathway.stages}
    ct_types          = {c.constraint_type for c in pathway.constraints}

    # Flag: CoMag recommended but hydraulic attenuation note says can't substitute
    if TI_COMAG in tech_in_stack and feasibility.supply_chain_risk == "High":
        eng_notes_text = " ".join(feasibility.key_risks)
        if "substitute" in eng_notes_text.lower() and "attenuation" in eng_notes_text.lower():
            pass  # CoMag IS a form of attenuation — no contradiction

    # Flag: settling recommended but no settling constraint identified
    settling_tech = {TI_INDENSE, TI_MIGINDENSE, TI_BIOMAG, TI_MEMDENSE}
    if settling_tech & tech_in_stack and CT_SETTLING not in ct_types and CT_MEMBRANE not in ct_types:
        flags.append(
            "Consistency: settling technology in stack but no settling constraint identified in constraint list. "
            "Verify that settling limitation was correctly classified from failure modes."
        )

    # Flag: DNF in stack but nitrification limitation unresolved
    if TI_DENFILTER in tech_in_stack:
        nit_resolved = any(t in tech_in_stack for t in (TI_IFAS, TI_HYBAS, TI_MBBR, TI_MABR, TI_MIGINDENSE))
        if not nit_resolved and CT_NITRIFICATION in ct_types:
            flags.append(
                "Consistency: Denitrification filter in stack but nitrification constraint is unresolved "
                "and no biofilm technology is present. DNF requires stable nitrification upstream."
            )

    # Flag: No alternatives if multi-constraint
    if pathway.multi_constraint and len(alternatives) < 2:
        flags.append(
            "Consistency: Multi-constraint plant with fewer than 2 alternatives — additional "
            "alternative pathway should be presented."
        )

    return flags


# ── Step 9: Final output assembly ─────────────────────────────────────────────

def build_credible_output(
    pathway: UpgradePathway,
    feasibility: FeasibilityReport,
    plant_context: Optional[Dict] = None,
) -> CredibleOutput:
    """
    Build the final credible, client-presentable output.

    Parameters
    ----------
    pathway : UpgradePathway
        Output of build_upgrade_pathway().

    feasibility : FeasibilityReport
        Output of assess_feasibility().

    plant_context : dict, optional
        Same dict passed to prior layers:
          flow_ratio, is_sbr, is_mbr, plant_size_mld, location_type.

    Returns
    -------
    CredibleOutput
        Does NOT modify pathway or feasibility.
    """
    ctx        = plant_context or {}
    flow_ratio = ctx.get("flow_ratio", 1.0) or 1.0

    all_notes:    List[CredibilityNote]       = []
    all_gen_alts: List[VerifiedAlternative]   = []

    # ── Step 1: Rule consistency ───────────────────────────────────────────────
    rule_notes, rule_alts = _check_rule_consistency(pathway, ctx)
    all_notes.extend(rule_notes)
    all_gen_alts.extend(rule_alts)

    # ── Step 2: Completeness ───────────────────────────────────────────────────
    comp_notes, comp_alts = _check_completeness(pathway)
    all_notes.extend(comp_notes)
    all_gen_alts.extend(comp_alts)

    # ── Step 3: Ensure ≥2 alternatives ────────────────────────────────────────
    verified_alts, alt_notes = _ensure_minimum_alternatives(
        pathway, all_gen_alts, feasibility)
    all_notes.extend(alt_notes)

    # ── Step 4: Compatibility flags ────────────────────────────────────────────
    compat_flags = _check_compatibility(pathway, ctx)

    # ── Step 5: Ranking clarification (always added) ──────────────────────────
    # (constant string, no computation needed)

    # ── Step 6: Structured residual risks ─────────────────────────────────────
    residual_risks = _build_residual_risks(pathway, feasibility, flow_ratio)

    # ── Step 7: Narrative ─────────────────────────────────────────────────────
    exec_sum    = _executive_summary(pathway, feasibility)
    why_works   = _why_stack_works(pathway)
    feas_narr   = _feasibility_narrative(feasibility)

    # ── Step 8: Consistency check ──────────────────────────────────────────────
    consistency = _consistency_check(pathway, feasibility, verified_alts)

    # ── Final confidence and ready flag ───────────────────────────────────────
    final_conf = feasibility.adjusted_confidence
    warnings   = [n for n in all_notes if n.severity in ("Warning", "Correction")]
    ready      = len(warnings) == 0 and len(consistency) == 0

    conf_stmt = (
        f"Recommendation confidence: {final_conf}. "
        f"{feasibility.confidence_reason} "
        + (f"Note: {len(warnings)} credibility warning(s) require review before client presentation. "
           if warnings else "No credibility issues identified — output is ready for client presentation.")
    )

    return CredibleOutput(
        pathway              = pathway,
        feasibility          = feasibility,
        recommended_stages   = list(pathway.stages),
        alternatives         = verified_alts,
        residual_risks       = residual_risks,
        credibility_notes    = all_notes,
        consistency_flags    = consistency,
        compatibility_flags  = compat_flags,
        executive_summary    = exec_sum,
        why_stack_works      = why_works,
        ranking_clarification= _RANKING_CLARIFICATION,
        feasibility_narrative= feas_narr,
        confidence_statement = conf_stmt,
        final_confidence     = final_conf,
        ready_for_client     = ready,
    )
